//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation:.
        /// </summary>
        internal static string Accommodation_ {
            get {
                return ResourceManager.GetString("Accommodation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Management.
        /// </summary>
        internal static string Accommodation_Management {
            get {
                return ResourceManager.GetString("Accommodation Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Name.
        /// </summary>
        internal static string Accommodation_Name {
            get {
                return ResourceManager.GetString("Accommodation Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Name:.
        /// </summary>
        internal static string Accommodation_Name_ {
            get {
                return ResourceManager.GetString("Accommodation Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Name:*.
        /// </summary>
        internal static string Accommodation_Name__ {
            get {
                return ResourceManager.GetString("Accommodation Name:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Statistics.
        /// </summary>
        internal static string Accommodation_Statistics {
            get {
                return ResourceManager.GetString("Accommodation Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Type:*.
        /// </summary>
        internal static string Accommodation_Type__ {
            get {
                return ResourceManager.GetString("Accommodation Type:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add accommodations.
        /// </summary>
        internal static string Add_accommodations {
            get {
                return ResourceManager.GetString("Add accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        internal static string Add_Image {
            get {
                return ResourceManager.GetString("Add Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Dates:*.
        /// </summary>
        internal static string Available_dates__ {
            get {
                return ResourceManager.GetString("Available dates:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Grade:.
        /// </summary>
        internal static string Average_Grade_ {
            get {
                return ResourceManager.GetString("Average Grade:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Renovation.
        /// </summary>
        internal static string Cancel_Renovation {
            get {
                return ResourceManager.GetString("Cancel Renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation Days Limit:.
        /// </summary>
        internal static string Cancelation_Days_Limit_ {
            get {
                return ResourceManager.GetString("Cancelation Days Limit:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation days limit:*.
        /// </summary>
        internal static string Cancelation_days_limit__ {
            get {
                return ResourceManager.GetString("Cancelation days limit:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        internal static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in Date.
        /// </summary>
        internal static string Check_in_Date {
            get {
                return ResourceManager.GetString("Check-in Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out Date.
        /// </summary>
        internal static string Check_out_Date {
            get {
                return ResourceManager.GetString("Check-out Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Reservations:.
        /// </summary>
        internal static string Check_Reservations_ {
            get {
                return ResourceManager.GetString("Check Reservations:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location.
        /// </summary>
        internal static string Choose_Location {
            get {
                return ResourceManager.GetString("Choose Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Accommodation:.
        /// </summary>
        internal static string Choose_Your_Accommodation_ {
            get {
                return ResourceManager.GetString("Choose Your Accommodation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Accommodation:*.
        /// </summary>
        internal static string Choose_your_Accommodation__ {
            get {
                return ResourceManager.GetString("Choose your Accommodation:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string City_ {
            get {
                return ResourceManager.GetString("City:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness:.
        /// </summary>
        internal static string Cleanliness_ {
            get {
                return ResourceManager.GetString("Cleanliness:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness:*.
        /// </summary>
        internal static string Cleanliness__ {
            get {
                return ResourceManager.GetString("Cleanliness:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Accommodation.
        /// </summary>
        internal static string Close_Accommodation {
            get {
                return ResourceManager.GetString("Close Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close accommodations.
        /// </summary>
        internal static string Close_accommodations {
            get {
                return ResourceManager.GetString("Close accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string Comment_ {
            get {
                return ResourceManager.GetString("Comment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:*.
        /// </summary>
        internal static string Comment__ {
            get {
                return ResourceManager.GetString("Comment:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Reservation Report.
        /// </summary>
        internal static string Download_Reservation_Report {
            get {
                return ResourceManager.GetString("Download Reservation Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of Renovation:*.
        /// </summary>
        internal static string Duration_of_Renovation__ {
            get {
                return ResourceManager.GetString("Duration of Renovation:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        internal static string End_date_ {
            get {
                return ResourceManager.GetString("End date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:*.
        /// </summary>
        internal static string End_Date__ {
            get {
                return ResourceManager.GetString("End Date:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Renovation Date:*.
        /// </summary>
        internal static string End_Renovation_Date__ {
            get {
                return ResourceManager.GetString("End Renovation Date:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following guidelines:*.
        /// </summary>
        internal static string Following_guidelines__ {
            get {
                return ResourceManager.GetString("Following guidelines:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the selected accommodation, choose start and end date you want the report for:.
        /// </summary>
        internal static string For_the_selected_accommodation_choose_start_and_end_date_you_want_the_report_for_ {
            get {
                return ResourceManager.GetString("For the selected accommodation choose start and end date you want the report for:" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest:.
        /// </summary>
        internal static string Guest_ {
            get {
                return ResourceManager.GetString("Guest:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Rating.
        /// </summary>
        internal static string Guest_Rating {
            get {
                return ResourceManager.GetString("Guest Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Reviews.
        /// </summary>
        internal static string Guest_Reviews {
            get {
                return ResourceManager.GetString("Guest Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Username.
        /// </summary>
        internal static string Guest_Username {
            get {
                return ResourceManager.GetString("Guest Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Username:.
        /// </summary>
        internal static string Guest_Username_ {
            get {
                return ResourceManager.GetString("Guest Username:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of renovation.
        /// </summary>
        internal static string History_of_renovation {
            get {
                return ResourceManager.GetString("History of renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to become a superowner, you must have at least 50 reviews and average grade of at least 4.5.
        /// </summary>
        internal static string In_order_to_become_a_superowner {
            get {
                return ResourceManager.GetString("In order to become a superowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least popular locations.
        /// </summary>
        internal static string Least_popular_locations {
            get {
                return ResourceManager.GetString("Least popular locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Renovation Request:.
        /// </summary>
        internal static string Level_of_Renovation_Request_ {
            get {
                return ResourceManager.GetString("Level of Renovation Request:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location - City:*.
        /// </summary>
        internal static string Location___City__ {
            get {
                return ResourceManager.GetString("Location - City:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location - State:*.
        /// </summary>
        internal static string Location___State__ {
            get {
                return ResourceManager.GetString("Location - State:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Guest Number:.
        /// </summary>
        internal static string Max_Guest_Number_ {
            get {
                return ResourceManager.GetString("Max Guest Number:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of guests:*.
        /// </summary>
        internal static string Max_number_of_guests__ {
            get {
                return ResourceManager.GetString("Max number of guests:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min number of reservation days:*.
        /// </summary>
        internal static string Min_number_of_reservation_days__ {
            get {
                return ResourceManager.GetString("Min number of reservation days:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Reservation Days:.
        /// </summary>
        internal static string Min_Reservation_Days_ {
            get {
                return ResourceManager.GetString("Min Reservation Days:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most occupied month:.
        /// </summary>
        internal static string Most_occupied_month_ {
            get {
                return ResourceManager.GetString("Most occupied month:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most occupied year:.
        /// </summary>
        internal static string Most_occupied_year_ {
            get {
                return ResourceManager.GetString("Most occupied year:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular locations.
        /// </summary>
        internal static string Most_popular_locations {
            get {
                return ResourceManager.GetString("Most popular locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Integrity:.
        /// </summary>
        internal static string Owner_Integrity_ {
            get {
                return ResourceManager.GetString("Owner Integrity:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Guest.
        /// </summary>
        internal static string Rate_Guest {
            get {
                return ResourceManager.GetString("Rate Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Guest:.
        /// </summary>
        internal static string Rating_Guest_ {
            get {
                return ResourceManager.GetString("Rating Guest:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovate.
        /// </summary>
        internal static string Renovate {
            get {
                return ResourceManager.GetString("Renovate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation.
        /// </summary>
        internal static string Renovation {
            get {
                return ResourceManager.GetString("Renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation Details:*.
        /// </summary>
        internal static string Renovation_details__ {
            get {
                return ResourceManager.GetString("Renovation details:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation recommended.
        /// </summary>
        internal static string Renovation_recommended {
            get {
                return ResourceManager.GetString("Renovation recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation Requests.
        /// </summary>
        internal static string Renovation_Requests {
            get {
                return ResourceManager.GetString("Renovation Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation Requests number:.
        /// </summary>
        internal static string Renovation_Requests_number_ {
            get {
                return ResourceManager.GetString("Renovation Requests number:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report numbers:.
        /// </summary>
        internal static string Report_numbers_ {
            get {
                return ResourceManager.GetString("Report numbers:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescheduling.
        /// </summary>
        internal static string Rescheduling {
            get {
                return ResourceManager.GetString("Rescheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        internal static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Rescheduling.
        /// </summary>
        internal static string Reservation_Rescheduling {
            get {
                return ResourceManager.GetString("Reservation Rescheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews number:.
        /// </summary>
        internal static string Reviews_number_ {
            get {
                return ResourceManager.GetString("Reviews number:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule renovation.
        /// </summary>
        internal static string Schedule_renovation {
            get {
                return ResourceManager.GetString("Schedule renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        internal static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the guest you want to rate:.
        /// </summary>
        internal static string Select_the_guest_you_want_to_rate_ {
            get {
                return ResourceManager.GetString("Select the guest you want to rate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the reservation request you want to accept/decline:.
        /// </summary>
        internal static string Select_the_reservation_request_you_want_to_accept_decline_ {
            get {
                return ResourceManager.GetString("Select the reservation request you want to accept/decline:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Guest.
        /// </summary>
        internal static string Selected_Guest {
            get {
                return ResourceManager.GetString("Selected Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        internal static string Start_date_ {
            get {
                return ResourceManager.GetString("Start date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:*.
        /// </summary>
        internal static string Start_Date__ {
            get {
                return ResourceManager.GetString("Start Date:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Renovation Date:*.
        /// </summary>
        internal static string Start_Renovation_Date__ {
            get {
                return ResourceManager.GetString("Start Renovation Date:*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string State_ {
            get {
                return ResourceManager.GetString("State:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics by Month.
        /// </summary>
        internal static string Statistics_by_Month {
            get {
                return ResourceManager.GetString("Statistics by Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics by Year.
        /// </summary>
        internal static string Statistics_by_Year {
            get {
                return ResourceManager.GetString("Statistics by Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationRescheduling.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superowner.
        /// </summary>
        internal static string Superowner {
            get {
                return ResourceManager.GetString("Superowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Type_ {
            get {
                return ResourceManager.GetString("Type:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Renovations.
        /// </summary>
        internal static string Upcoming_renovations {
            get {
                return ResourceManager.GetString("Upcoming renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Forum!.
        /// </summary>
        internal static string Useful_Forum_ {
            get {
                return ResourceManager.GetString("Useful Forum!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to become a useful forum, there must be at least 10 owners&apos; comments and at least 20 guests&apos; comments.
        /// </summary>
        internal static string usefulForumMessage {
            get {
                return ResourceManager.GetString("usefulForumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a Superowner!.
        /// </summary>
        internal static string You_are_a_Superowner {
            get {
                return ResourceManager.GetString("You are a Superowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Accommodations.
        /// </summary>
        internal static string Your_Accommodations {
            get {
                return ResourceManager.GetString("Your Accommodations", resourceCulture);
            }
        }
    }
}
